### ISSUE TITLE
[INTAKE] Cloud Resource pack documentation & release note Sprint wise

### ISSUE THREAD

**Issue by ppradhan9** [chef/chef-web-docs#3067]
## Project Plan: Cloud Resource Pack Recurring Documentation Review.
We have a 2 weeks Sprint cycle for Cloud Compliance (Cloud Resource Pack).
We request 2 items from Documentation Team.
1. On Each Thursday we would need documentation review on the PR we raise.
2. Release note (if any) for cloud resource packs at end of each Sprint.

**Resource Packs includes - Inspec AWS / Inspec Azure / Inspec Gcp.**
  

## Project overview

**Tell us about the project:**

Product name: Cloud Resource Pack
Product code name: Compliance
Brief product description: This group of products creates resource pack for inspec to audit cloud resource(AWS/Azure/Gcp)
Project status page: **NA**
Business requirements doc: **NA**
Design documents: **NA**
Functional analysis documents: **NA**

## Business group

**Which business does this project fall under:**

Business group: (ex. product, engineering, marketing)
Team:

## Product
- [ ] Chef Automate
- [ ] Chef Habitat
- [ ] Chef Infra Client
- [ ] Chef Infra Server
- [ ] Chef InSpec
- [x] Other : Compliance

## Product team

**Compliance Team:**

Product manager: Lokesh K
Project manager: **NA**
Software developers: Soumyodeep , Nirbhay , Satish Babu , Pradipta Pradhan
Quality assurance : Soumyodeep , Nirbhay , Satish Babu , Pradipta Pradhan
Marketing: **NA**
Developer outreach: 
Legal:
Field engineer:
Evangelist:
Security:

## Priority

Is this documentation a strategic priority: Yes

Does this project roll up under a strategic leadership goal? If so, which one?

## Target users

**Who is the documentation for:**

- [ ] Sysadmins
- [x ] Developers
- [ x] Internal engineers
- [ ] Business decision-makers

## Issue tracking

**Where can the tech writer track work related to the project:**

GitHub Repository: https://github.com/inspec/inspec-aws , https://github.com/inspec/inspec-azure , https://github.com/inspec/inspec-gcp
Issue link(s):
PR link(s): 
AHA! link(s): https://chef.aha.io/releases/COMPL-R-2 , https://chef.aha.io/releases/COMPL-R-3 ..etc

## Release timelines

Beta partner release date:
General availability (GA) launch date:
Date docs must be ready to distribute:

## Information sources

**How does information flow within your team:**

Key team meetings:
Team sprints: 
Scrum leader:
Email lists: Cloud Resource Packs - Chef Compliance Content Team <945de1cb.progress.com@amer.teams.ms>
Slack channels: cloud-resource-packs-aaaadntdrrq3b6naeayhlba6qq@chefio.slack.com

## Code repositories

**Where the code is stored:**
docs/resources folder on each repository

Repository:
Relevant directories and files:

## Testing

**How do we validate the product:**

Test environment:
Test scripts:
Terraform or Vagrantfiles:

**How do we report problems:**

## Will this documentation be public or protected:

Protected behind a login: y/n
Public to everyone: y/n

## Documentation size estimate

**How much documentation do you anticipate for this project:**

## Scope of content requests

**What type of content do you need:**

Documentation: y
UX microcopy: n
Screencasts: n
Email campaign content: n
Blog articles: y
Other: n

## Reviewers for content

**Who will provide the technical review for the docs and other content:

Person 1: Someone from the Documentation Team
Person 2: Someone from the Documentation Team

## Support post-launch

**Compliance team**

Support team:
Is the support aware of this project: y
Long-term owner post-launch: Pradipta Pradhan

## Internal product wiki/resource pages

**What wiki/resource pages are important to be aware of for this project:**

page: **NA**
page: **NA**
page: **NA**

## Marketing support

Do you need Marketing support? n
Have you reached out to anyone in Marketing? n
If yes, who is the Marketing contact for this project: unaware 

## Other

**List any other details not requested above that might be important to know.**
