### ISSUE TITLE
[INTAKE] Custom Resources Documentation needs a rethink

### ISSUE THREAD

**Issue by damacus** [chef/chef-web-docs#3124]
# Documentation project plan

- Custom Resources currently sprawl across multiple pages
- We should rewrite them from the ground up taking what is required from the old documentation
- Separate out upgrading from definitions/LWRPS into their owns docs
- Write a simple getting started guide
- Write a more complex guide with gotchyas (e.g. accumulators)
- A complete DSL guide with a full terms of reference

## Product

Chef Infra Client

Brief product description: [3-4 lines]

Product manager: @tas50

### Target users

- [x] Sysadmins
- [x] Developers
- [x] Internal engineers
- [ ] Business decision-makers

### Documentation size estimate

~ 5 pages

### Reviewers for content

- @tas50
- @lamont-granquist
- @Xorima / @bmhughes

## Actions

- [ ] Document migration from LWRP to Custom Resources
- [ ] Document migration from definitions to Custom Resources
- [ ] new\_resource vs current resource
- [ ] Libraries
- [ ] action\_class
- [ ] Accumulators

## Review Exiting Community Documentation

- [ ] [Chef Custom Resources - Missing Documentation](https://blog.backslasher.net/chef-custom-resources.html)
