### ISSUE TITLE
Update Hugo and improve docs build Netlify script

### ISSUE THREAD

**Issue by IanMadd** [chef/chef-web-docs#3125]
## General details

Bump Hugo to 0.83.1
Fix issue where old pages that may have been deleted or renamed are still built.

- [x] chef/chef-server#2465
- [x] inspec/inspec#5507
- [x] chef/desktop-config#359
- [x] chef/chef-workstation#1966
- [x] chef/automate#5043
- [x] habitat-sh/habitat#8190
- [x] #3167

**Comment by IanMadd** [comment]
Everything is at 0.83.1
