### ISSUE TITLE
[INTAKE] ServiceNow Application, Notification, and Data Feed documentation

### ISSUE THREAD

**Issue by vivek-yadav** [chef/chef-web-docs#3196]
To request support for a large documentation project:

1. Fill in the `Documentation project plan` and open an issue
2. Send an email with the rest of the information in this template (as much as you have) to docs@chef.io. 

We will follow up with you soon!

## Steps

- [x] ServiceNow integration docs
- [ ]  ServiceNow notification docs
- [x] ServiceNow navigation
- [ ] Data Feed documentation

## Documentation project plan

This project plan defines the scope and details for a larger doc project. Complete as much information as you can, as this will help us get better oriented and familiar with the doc needs.

## Product
[*] Chef Automate
[ ] Chef Habitat
[ ] Chef Infra Client
[ ] Chef Infra Server
[ ] Chef InSpec
[ ] Other________________

Brief product description: [3-4 lines]

[ ] New ServiceNow Chef Automate Integration App page.
[ ] Improvement of existing Chef Automate Incident App page.
[ ] Expansion of Existing Data Feed Setting page.
[ ] Changes to Navigation for Data Feed and ServiceNow Apps.

We had a feature (Data Feed) of sending data from Chef Automate to ServiceNow or some other webhook based service.
This feature is behind a feature flag. Now we are working on it to make it GA. 
This has multiple integration options:
1. Webhook Based
    a. ServiceNow
    b. Splunk
    c. ELK
    d. Custom Webhook
2. Storage Based
    a. S3
    b. Minio

Product manager: Ankur Mundhra

### Project overview

**Tell us about the project:**

Product name: Chef Automate Data Feed
Product code name: 

Project status page: 
Business requirements doc:
Design documents:
Functional analysis documents:

### Business group

**Which business does this project fall under:**

Business group: (ex. product, engineering, marketing)
Team: SN/Data Feed Team

### Product team

**Who’s who on the project team:**

Product manager: Ankur Mundhra
Project manager: Vivek Yadav
Software developers: 
Quality assurance:
Marketing:
Developer outreach:
Legal:
Field engineer:
Evangelist:
Security:

### Priority

Is this documentation a strategic priority: Yes, Committed for Q3 2021.

Does this project roll up under a strategic leadership goal? If so, which one? 

### Target users

**Who is the documentation for:**

[*] Sysadmins
[ ] Developers
[ ] Internal engineers
[ ] Business decision-makers

### Issue tracking

**Where can the tech writer track work related to the project:**

GitHub Repository: 
Issue link(s): Epic : [Data Feed](https://github.com/chef/automate/issues/4733)               Story: [Doc on Chef Automate Integration App on ServiceNow](https://github.com/chef/automate/issues/5176)
PR link(s):
AHA! link(s):

### Release timelines

Beta partner release date:
General availability (GA) launch date: This will be released in a phased manner, over the 2 months period.
Date docs must be ready to distribute: We will need the docs team's engagement to start 7th June, 2021. And it can span over 2 months, as the incremental features keep releasing.

### Information sources

**How does information flow within your team:**

Key team meetings:
Team sprints:
Scrum leader:
Email lists:
Slack channels:

### Code repositories

**Where the code is stored:**

Repository:
Relevant directories and files:

### Testing

**How do we validate the product:**

Test environment:
Test scripts:
Terraform or Vagrantfiles:

**How do we report problems:**

### Will this documentation be public or protected:

Protected behind a login: y/n
Public to everyone: y/n

### Documentation size estimate

**How much documentation do you anticipate for this project:**
1. New ServiceNow Chef Automate Integration App page.
2. Improvement of existing Chef Automate Incident App page.
3. Expansion of Existing Data Feed Setting page.
4. ReThinking on IA(Information Architecture) of Data Feed and ServiceNow Apps.

### Scope of content requests

**What type of content do you need:**

Documentation: y/n
UX microcopy: y/n
Screencasts: y/n
Email campaign content: y/n
Blog articles: y/n
Other: y/n

### Reviewers for content

**Who will provide the technical review for the docs and other content:

Person 1: Vivek Yadav
Person 2: Vivek Shankar

### Support post-launch

**Who will support the product post-launch:**

Support team:
Is the support aware of this project: y/n
Long-term owner post-launch:

### Internal product wiki/resource pages

**What wiki/resource pages are important to be aware of for this project:**

page:
page:
page:

### Marketing support

Do you need Marketing support? y/n
Have you reached out to anyone in Marketing? y/n
If yes, who is the Marketing contact for this project:

### Other

**List any other details not requested above that might be important to know.**

**Comment by kagarmoe** [comment]
I abbreviated the title to represent the current work. We will need new intake forms for future work.

**Comment by kagarmoe** [comment]
I'm going to close this as completed. The issue was a bit too large and we've completed most of et. Please open an issue specifically for the Event Feed when you're ready to begin that work.
