### ISSUE TITLE
[INTAKE]Cloud resource Document review Sprint May 31-Jun11 2021

### ISSUE THREAD

**Issue by ppradhan9** [chef/chef-web-docs#3197]
## General details

Link to page & section that needs updated: [https://github.com/inspec/inspec-aws](https://github.com/inspec/inspec-aws) , [https://github.com/inspec/inspec-azure](https://github.com/inspec/inspec-azure) , [https://github.com/inspec/inspec-gcp](https://github.com/inspec/inspec-gcp) Business group: Engineering Product owner: Pradipta Pradhan Team: Cloud Compliance Date update needs to be published: June 11 , 2021

## Product

- [ ] Chef Automate
- [ ] Chef Habitat
- [ ] Chef Infra Client
- [ ] Chef Infra Server
- [ ] Chef InSpec
- [ ] Chef Workstation
- [ ] Other: Chef Compliance

## Update details

Describe the update that needs to be made. Be as specific as possible: Need to Doc review for the following

[Added Support for Azure Streaming Jobs function](https://github.com/inspec/inspec-azure/pull/375) [Support azure functions resource](https://github.com/inspec/inspec-azure/pull/370) AWS::ApiGateway::Deployment AWS::ApiGateway::Method AWS::ApiGateway::RestApi AWS::Athena::WorkGroup AWS::AutoScaling::ScalingPolicy AWS::Batch::ComputeEnvironment AWS::Batch::JobDefinition AWS::Batch::JobQueue AWS::Cognito::IdentityPool AWS::Cognito::UserPool AWS::Cognito::UserPoolClient AWS::DMS::Endpoint AWS::DMS::ReplicationInstance AWS::DMS::ReplicationSubnetGroup AWS::ECS::Service AWS::ECS::TaskDefinition AWS::EFS::MountTarget AWS::ElasticLoadBalancingV2::Listener AWS::ElasticLoadBalancingV2::ListenerCertificate AWS::ElasticLoadBalancingV2::ListenerRule AWS::ElasticLoadBalancingV2::LoadBalancer AWS::ElasticLoadBalancingV2::TargetGroup AWS::Elasticsearch::Domain AWS::Events::Rule AWS::Glue::Crawler AWS::Glue::Database AWS::IAM::InstanceProfile

## Existing resources

GitHub Repository: [https://github.com/inspec/inspec-aws](https://github.com/inspec/inspec-aws) , [https://github.com/inspec/inspec-azure](https://github.com/inspec/inspec-azure) Issue link(s): [https://progresssoftware-my.sharepoint.com/:x:/g/personal/garmoe\_progress\_com/EecxRwVjzU1KgOg4lbK48xgBJ\_Y3yVKfYE\_qcvQDg-w4IA?e=zRwFLv](https://progresssoftware-my.sharepoint.com/:x:/g/personal/garmoe_progress_com/EecxRwVjzU1KgOg4lbK48xgBJ_Y3yVKfYE_qcvQDg-w4IA?e=zRwFLv) PR link(s): AHA! link(s): Other draft documentation: Related design, business docs, or other information:

## Review

Name of technical reviewer:
