### ISSUE TITLE
[INTAKE] Improve Chef Desktop documentation

### ISSUE THREAD

**Issue by rishichawda** [chef/chef-web-docs#3216]
## General details

Link to page & section that needs updated: https://docs.chef.io/desktop/
Business group: (ex. product, engineering, marketing) product
Product owner: Nischal Reddy
Team: Chef Desktop
Date update needs to be published: July 15

## Product
- [ ] Chef Automate
- [ ] Chef Habitat
- [ ] Chef Infra Client
- [ ] Chef Infra Server
- [ ] Chef InSpec
- [ ] Chef Workstation
- [x] Other: Chef Desktop

## Update details

Describe the update that needs to be made. Be as specific as possible:

Minor refactor of the Chef Desktop documentation's menu based on the changes in the content.
This update contains following: 

- Restructured the documentation to give a better flow
- Added a new section for getting started through terraform scripts
## Existing resources

GitHub Repository: https://github.com/chef/desktop-config (desktop documentation), https://github.com/chef/chef-desktop-quick-setup (terraform scripts)
Issue link(s): 
PR link(s): https://github.com/chef/chef-web-docs/pull/3164, https://github.com/chef/desktop-config/pull/366
AHA! link(s): https://chef.aha.io/epics/DESK-E-3
Other draft documentation: 
Related design, business docs, or other information: https://progresssoftware.sharepoint.com/:w:/s/ChefCoreC/ERGd5_FwKLpNo9K28SV7fNUBXAxFSxRdtir5OTTaN69kfw?e=MvyvVl

## Review

Name of technical reviewer:
