### ISSUE TITLE
[INTAKE] InSpec Cloud Resource Release Notes

### ISSUE THREAD

**Issue by ppradhan9** [chef/chef-web-docs#3219]
## General details
Having an insight to publish a release of Content(Release Note for list of content published so far) delivered in quarterly or half yearly way.
It can be part of automate or independent. 

I have similar thought to showcase Cloud Resource Pack in Inspec if possible.
We can talk through the challenges anytime.

Link to page & section that needs updated:
Business group: (ex. product, engineering, marketing)
Product owner:
Team:
Date update needs to be published:

## Product
- [ ] Chef Automate
- [ ] Chef Habitat
- [ ] Chef Infra Client
- [ ] Chef Infra Server
- [ ] Chef InSpec
- [ ] Chef Workstation
- [x] Other:Compliance Content

## Update details

Describe the update that needs to be made. Be as specific as possible:

## Existing resources

GitHub Repository: https://github.com/chef/compliance-profiles , https://github.com/inspec/inspec-aws , https://github.com/inspec/inspec-azure , https://github.com/inspec/inspec-gcp , https://github.com/inspec/inspec-alicloud ...
Issue link(s):
PR link(s):
AHA! link(s):
Other draft documentation:
Related design, business docs, or other information:

## Review

Name of technical reviewer:

**Comment by kagarmoe** [comment]
@IanMadd Can you copy the scripts over to the rest of the cloud resource repos & make sure the wikis are set up?

**Comment by kagarmoe** [comment]
We're as automated as we're going to get for these.
