### ISSUE TITLE
Implement Content-Security-Policy Header

### ISSUE THREAD

**Issue by kagarmoe** [chef/chef-web-docs#3501]
## General details

We need to implement the `Content-Security-Policy` header in our configuration. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

- [ ] Do we need to fix our javascript?
- [ ] If so, how do we fix it? 
- [ ] What files need fixed?
- [ ] What are all of the sources for our content?

Related PR:
https://github.com/chef/chef-web-docs/pull/3497
